In [1]:
import numpy as np 

In [5]:
#1.创建一个有101个元素的一维数组，此数组是由“一个起始值为2，截止值为80（包括截止值）的等差数列”转换而来的。
a1=np.linspace(2,80,101)
a1

array([ 2.  ,  2.78,  3.56,  4.34,  5.12,  5.9 ,  6.68,  7.46,  8.24,
        9.02,  9.8 , 10.58, 11.36, 12.14, 12.92, 13.7 , 14.48, 15.26,
       16.04, 16.82, 17.6 , 18.38, 19.16, 19.94, 20.72, 21.5 , 22.28,
       23.06, 23.84, 24.62, 25.4 , 26.18, 26.96, 27.74, 28.52, 29.3 ,
       30.08, 30.86, 31.64, 32.42, 33.2 , 33.98, 34.76, 35.54, 36.32,
       37.1 , 37.88, 38.66, 39.44, 40.22, 41.  , 41.78, 42.56, 43.34,
       44.12, 44.9 , 45.68, 46.46, 47.24, 48.02, 48.8 , 49.58, 50.36,
       51.14, 51.92, 52.7 , 53.48, 54.26, 55.04, 55.82, 56.6 , 57.38,
       58.16, 58.94, 59.72, 60.5 , 61.28, 62.06, 62.84, 63.62, 64.4 ,
       65.18, 65.96, 66.74, 67.52, 68.3 , 69.08, 69.86, 70.64, 71.42,
       72.2 , 72.98, 73.76, 74.54, 75.32, 76.1 , 76.88, 77.66, 78.44,
       79.22, 80.  ])

In [6]:
#2.把上题中的一维数组改为10*11的二维数组，不够的元素用0补充
a2= np.zeros((10, 11), dtype=int)  
a2.ravel()[:101] = a1
print(a2)

[[ 2  2  3  4  5  5  6  7  8  9  9]
 [10 11 12 12 13 14 15 16 16 17 18]
 [19 19 20 21 22 23 23 24 25 26 26]
 [27 28 29 30 30 31 32 33 33 34 35]
 [36 37 37 38 39 40 41 41 42 43 44]
 [44 45 46 47 48 48 49 50 51 51 52]
 [53 54 55 55 56 57 58 58 59 60 61]
 [62 62 63 64 65 65 66 67 68 69 69]
 [70 71 72 72 73 74 75 76 76 77 78]
 [79 80  0  0  0  0  0  0  0  0  0]]


In [3]:
#3.创建长度为5的整型全一向量
a3=np.ones(5)
print(a3)

[1. 1. 1. 1. 1.]


In [18]:
#4.创建一个长度为10的零向量，并把第五个值赋值为1。
a4= np.zeros((10), dtype=int) 
a4[4]=1
print(a4)

[0 0 0 0 1 0 0 0 0 0]


In [19]:
#5.创建一个值域为10到49的向量，步长为0.5。
a5=np.linspace(10,49,79)
print(a5)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5 30.  30.5
 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5 37.  37.5
 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5 43.  43.5 44.  44.5
 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49. ]


In [20]:
#6.将上一个向量进行反转（第一个元素变为最后一个元素，第二个元素变为倒数第二个元素，等等）。
a6=a5[::-1]
print(a6)

[49.  48.5 48.  47.5 47.  46.5 46.  45.5 45.  44.5 44.  43.5 43.  42.5
 42.  41.5 41.  40.5 40.  39.5 39.  38.5 38.  37.5 37.  36.5 36.  35.5
 35.  34.5 34.  33.5 33.  32.5 32.  31.5 31.  30.5 30.  29.5 29.  28.5
 28.  27.5 27.  26.5 26.  25.5 25.  24.5 24.  23.5 23.  22.5 22.  21.5
 21.  20.5 20.  19.5 19.  18.5 18.  17.5 17.  16.5 16.  15.5 15.  14.5
 14.  13.5 13.  12.5 12.  11.5 11.  10.5 10. ]


In [21]:
#7.创建一个3x3的矩阵，值域为0到8。
a7= np.arange(0,9).reshape(3,3)
print(a7)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
#8.将上题中4、5两个元素切出来。
a8=a7[[1,1],[1,2]]
a8

array([4, 5])

In [23]:
#9.创建一个3x2的二维数组。
a9=np.ones(6).reshape(3,2)
print(a9.astype(int))


[[1 1]
 [1 1]
 [1 1]]


In [24]:
#10.创建一个10*10的2维数组，该数组边界值为0，内部的值为1。
a10 = np.ones((5, 5), dtype=int)  
a10[[0,-1 ],...] = 0 
a10[...,[-1,0]] = 0 
a10

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [42]:
#11.一个5x3的数组和一个3x2的数组是否可以相乘，如果可以写出相乘之后数组的形状，如果不可以请说出理由。
b1=np.arange(15).reshape(5,3)
b2=np.arange(6).reshape(3,2)
b1*b2==b3
print(b3)
#答案：不可以，返回形状不匹配，具体返回operands could not be broadcast together with shapes (5,3) (3,2)

ValueError: operands could not be broadcast together with shapes (5,3) (3,2) 

In [53]:
#12.一个5x1x4的数组和一个4x4的数组是否可以相加，如果可以写出相加之后数组的形状，如果不可以请说出理由。
c1 = np.zeros(16).reshape(4,4)
c2 = np.full((5, 1, 4), 3)  
print(c1+c2)

[[[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]]


In [10]:
#13.创建一个值域为20到49的一维数组，将此数组转换为5*2*3的三维数组。
a13= np.arange(20,50).reshape(5,2,3)
a13

array([[[20, 21, 22],
        [23, 24, 25]],

       [[26, 27, 28],
        [29, 30, 31]],

       [[32, 33, 34],
        [35, 36, 37]],

       [[38, 39, 40],
        [41, 42, 43]],

       [[44, 45, 46],
        [47, 48, 49]]])

In [11]:
#14.罗列出2^2,2^3,2^4，一直到2^30。
a14=np.logspace(2,30,29,base=2)
a14

array([4.00000000e+00, 8.00000000e+00, 1.60000000e+01, 3.20000000e+01,
       6.40000000e+01, 1.28000000e+02, 2.56000000e+02, 5.12000000e+02,
       1.02400000e+03, 2.04800000e+03, 4.09600000e+03, 8.19200000e+03,
       1.63840000e+04, 3.27680000e+04, 6.55360000e+04, 1.31072000e+05,
       2.62144000e+05, 5.24288000e+05, 1.04857600e+06, 2.09715200e+06,
       4.19430400e+06, 8.38860800e+06, 1.67772160e+07, 3.35544320e+07,
       6.71088640e+07, 1.34217728e+08, 2.68435456e+08, 5.36870912e+08,
       1.07374182e+09])

In [12]:
#15.产生下图中的二维数组A。图片自己翻题目看吧
a15=np.linspace(0,38,20,dtype=int)
print(a15.reshape(4,5))

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]


In [13]:
#16通过对A切片，获得下面数组。
a16=a15.reshape(4,5)
print(a16[1, :])
print(a16[3, :])

[10 12 14 16 18]
[30 32 34 36 38]


In [14]:
#17通过对A切片，获得下面数组。
a17=a16[...,0:3]
a17

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24],
       [30, 32, 34]])

In [15]:
#18.通过对A切片，获得下面数组。
a18=a16[
    [0,1,1,3,2,0],[1,0,4,4,1,3]
]
a18

array([ 2, 10, 18, 38, 22,  6])

In [16]:
#a19.使用切片赋值语句将数组A改为下面数组。
a16[...,0]=11
print(a16)

[[11  2  4  6  8]
 [11 12 14 16 18]
 [11 22 24 26 28]
 [11 32 34 36 38]]


In [17]:
#20.从数组[1, 2, 0, 0, 4, 0,-5]中找出非0元素。
a20=np.array([1,2,0,0,4,0,-5])
print(a20[a20!=0])

[ 1  2  4 -5]
